### ISSUE TITLE
Is this still in active development?

### ISSUE THREAD

**Issue by holisticnetworking** [8fold/php-html#97]
Seems quiet here for the past year?

**Comment by joshbruce** [comment]
Hey @holisticnetworking,

Yeah. Few reasons for that, I suppose:

1. I think I'm the only one using this library in production.
2. It's actually one of a suite of three. https://github.com/8fold/php-html-component is the base. This is the mid-tier, so to speak. https://github.com/8fold/php-uikit is the high-level and one getting hit with the most changes still.
3. It's a library for spitting out HTML5, which is pretty stable; so, not much to change and I haven't run into any real problems...maybe it's just stable enough...it does need to be updated eventually for HTML 5.1 and 5.2 elements.
4. I recently took on being a maintainer over at Marked; so, that's been occupying a lot of time. https://github.com/markedjs/marked

Appreciate the interest. Rest assured, it is alive and maintained (the site is out of date compared to the 3.0 release - long story).

As this issue seems to be a touch point not a feature request, issue report, or similar, I will be closing the issue. Thank you again!

**Comment by joshbruce** [comment]
ps. I'm also a pretty big proponent of the UNIX philosophy of development: https://en.wikipedia.org/wiki/Unix_philosophy

If you think 8fold Elements is lacking in some way, please let me know (or submit a PR).
